core/models/delivery.py
#!/usr/bin/env python3
'''
    File location: /core/models/delivery.py
    Declares Delivery model
'''

core/models/optimization.py
#!/usr/bin/env python3
'''
    File location: /core/models/optimization.py
    Declares OptimizedRoute model
'''

from core.extensions import db
from sqlalchemy import ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

class OptimizedRoute(db.Model):
    __tablename__ = 'optimized_routes'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, ForeignKey('users.id'), nullable=False)
    route = db.Column(db.Geometry('LINESTRING', srid=4326), nullable=False)
    created_at = db.Column(db.TIMESTAMP, server_default=func.now(), nullable=False)

    # Define the relationship with the User model
    user = relationship('User', back_populates='optimized_routes')

    def __init__(self, user_id, route):
        self.user_id = user_id
        self.route = route

core/models/user.py
#!/usr/bin/env python3
'''
    File location: /core/models/user.py
    Declares User model
'''

from flask_login import UserMixin
from core.extensions import db
from werkzeug.security import generate_password_hash, check_password_hash

class User(UserMixin, db.Model):
    """
    User model
    """

    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(
        db.String(255), unique=True, nullable=False)
    email = db.Column(db.String(
        255), unique=True, nullable=False)
    first_name = db.Column(db.String(100))
    last_name = db.Column(db.String(100))
    password_hash = db.Column(db.String(255), nullable=False)
    created_at = db.Column(
        db.TIMESTAMP, server_default=db.func.now())
    last_updated_at = db.Column(
        db.TIMESTAMP, onupdate=db.func.current_timestamp())

    def __init__(self, username, email, first_name, last_name, password):
        self.username = username
        self.email = email
        self.first_name = first_name
        self.last_name = last_name
        self.password_hash = generate_password_hash(password, method='sha256')

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'<User "{self.username}">'

core/__init__.py
from flask import Flask
from config import Config
from core.extensions import db
from flask_login import LoginManager

def create_app(config_class=Config):
    '''
    Initializes and registers blueprints
    '''
    app = Flask(__name__)
    app.config.from_object(config_class)

    # Initializing Flask extensions
    db.init_app(app)

    # Registering blueprints
    from core.main import main_bp # main blueprint
    app.register_blueprint(main_bp)

    from core.auth import auth_bp # auth blueprint
    app.register_blueprint(auth_bp)

    from core.optimization import get_route_bp # optimization blueprint
    app.register_blueprint(get_route_bp)

    from core.deliveries import delivery_bp # deliveries blueprint
    app.register_blueprint(delivery_bp)

    # Specify user loader
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    from core.models.user import User

    @login_manager.user_loader
    def load_user(id):
        # Get the user
        return User.query.get(int(id))

    @app.route('/test/')
    def test_page():
        return '<h1>Testing the Flask Application Factory Pattern</h1>'

    return app

core/deliveries/__init__.py
from flask import Blueprint

delivery_bp = Blueprint('deliveries', __name__, url_prefix='/deliveries')


from core.deliveries import delivery_routes

core/main/__init__.py
from flask import Blueprint


main_bp = Blueprint('main', __name__, url_prefix='/main')

from core.main import routes

core/main/routes.py
#!/usr/bin/env python3
'''
    File location: /core/main/routes.py
    Declares landing page main routes
'''

from flask import render_template
from flask_login import login_required, current_user
from core.main import main_bp
from core.extensions import db

@main_bp.route('/')
def index():
    """
    Landing page
    """
    return render_template('index.html')

@main_bp.route('/profile')
@login_required
def profile():
    """
    Current user's profile
    """

    # Get the current user's first name
    first_name = current_user.first_name
    return render_template('profile.html', first_name=first_name)

core/optimization/__init__.py
from flask import Blueprint

get_route_bp = Blueprint('route', __name__, url_prefix='/route')


from core.optimization import get_routes

core/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>RouteRover</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <style>
        /* CSS for left-aligning password requirements */
        .password-requirements {
            text-align: left;
            font-size: 12px;
            margin-bottom: 10px;
        }
    </style>
</head>

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('main.index') }}" class="navbar-item">
                                Home
                            </a>
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('main.profile') }}" class="navbar-item">
                                Profile
                            </a>
                            <a href="{{ url_for('route.get_route') }}" class="navbar-item">
                                Get Route
                            </a>
                            {% endif %}
                            {% if not current_user.is_authenticated %}
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                                Logout
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

core/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
    RouteRover
</h1>
<h2 class="subtitle">
    Your route planning companion
</h2>
{% endblock %}

core/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="notification is-danger">
            {{ messages[0] }}
        </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/auth/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="login_input" placeholder="Your Email or Username"
                        autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox" name="remember">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

core/templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
    Welcome, {{ first_name }}!
</h1>
{% endblock %}

core/templates/route.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Get Shortest Route</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="notification is-danger">
            {{ messages[0] }}
        </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/route/get-route">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="start_point_coords" placeholder="Starting Point"
                        autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="end_point_coords" placeholder="Destination">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <label>Mode of Travel:</label>
                    <select id="mode_of_travel" name="mode_of_travel">
                        <option value="Walk">Walk</option>
                        <option value="Bike">Bike</option>
                        <option value="Drive">Drive</option>
                        <select>
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Find Route</button>
        </form>
    </div>
</div>
{% endblock %}

core/templates/signup.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="notification is-danger">
            {{ messages[0] }}. Refresh <a href="{{ url_for('auth.signup') }}">signup page</a>.
        </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/auth/signup">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="username" placeholder="Username" autofocus=""
                        required>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="" required>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="first_name" placeholder="First Name" autofocus=""
                        required>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="last_name" placeholder="Last Name" autofocus=""
                        required>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password" required
                        aria-describedby="password-requirements">
                </div>
            </div>

            <!-- Display password requirements -->
            <div id="password-requirements" class="password-requirements">
                <p class="help"><b>Password Requirements:</b></p>
                <ul class="password-requirements">
                    <li>At least 8 characters</li>
                    <li>At least one uppercase letter</li>
                    <li>At least one lowercase letter</li>
                    <li>At least one digit</li>
                    <li>At least one special character (!@#$%^&*()_-+=<>?/[]{}|)</li>
                </ul>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Submit</button>
        </form>
    </div>
</div>
{% endblock %}